title: Meu blog
linkedin: https://linkedin.com/in/daniirocca
description: >-
  Bem-vindo ao meu blog! Sou apaixonada por ciência e tecnologia, e aqui compartilho aprendizados em programação, dados e química aplicada.
baseurl: "/blog"
url: "https://daniirocca.github.io"
github_username: daniirocca

theme: minima

plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    github: daniirocca
    linkedin: daniirocca

author: Daniela Rocca
email: contato@exemplo.com
